### ISSUE TITLE
RPGO_RebuildSelectedSoldier causes soldier specs to be rerolled randomly on every promotion afterwards

### ISSUE THREAD

**Issue by ansabalirai** [Musashi1584/RPGO#42]
As mentioned on Discord, apparently using rpgo console command to reroll specs leads to the specs being rerolled again everytime when the soldier is promoted afterwards. Seems to happen with random classes as well as commander's choice, so likely SWO agnostic.

**Comment by ansabalirai** [comment]
Another suggestion mentioned in discord is to allow for optionally keeping the same specializations when rerolling and just rebuilding based on any modified perks lineup in the config. It is an admittedly corner case but would be helpful when testing out different builds in an ongoing campaign (specifically for the random classes and spec roulette SWOs)

**Comment by Musashi1584** [comment]
- Fixed RPGO_RebuildSelectedSoldier causes soldier specs to be rerolled randomly on every promotion afterwards

- Changes RPGO_RebuildSelectedSoldier command to

RPGO_RebuildSelectedSoldier <OPTIONAL_PreserveSquaddiePerks> <OPTIONAL_PreserveSpecializations> <OPTIONAL_SetRankTo> <OPTIONAL_ChangeClassTo>

the new parameter "PreserveSpecializations" allows to you to keep the prior specializations of the soldier

**Comment by ansabalirai** [comment]
So it seems like this issue is still not resolved. Attached find the log where Ronan has the sentry spec but in after mission promotion, reverts tp older specs before they were rerolled.
I am playing with random classes btw
[Launch.log](https://github.com/Musashi1584/RPGO/files/4732719/Launch.log)

**Comment by ansabalirai** [comment]
That is strange since RPGO is typically such a big overhaul that it doesn't really play well with other mods that tinker with soldier class and rank progression, etc. I am not playing with LWOTC or CI, the two big overhauls that I know of which might cause this issue. In any case, I will keep playing and see if it is a persistent, reproducible issue at my end. I am using additional soldier console commands mod which I used to level up the soldier from rookie, but I am not sure if that can be the culprit here?

**Comment by bstar1million** [comment]
RPG Overhaul has its own console commands to rebuild and/or level up soldiers. You should use those.

**Comment by ansabalirai** [comment]
I should mention that I am indeed using the rpgo console commands to respec. I just used the levelupselectedsoldier command to promote from rookie to the 'soldier' class
